/**
  ******************************************************************************
  * @file           : system_clock_config.h
  * @brief          : Header for system_clock_config.c file.
  *                   This file contains the common defines of the system clock configuration module.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 Henny Penny.
  * All rights reserved.
  *
  ******************************************************************************
  */

#ifndef SYSTEM_CLOCK_CONFIG_H_
#define SYSTEM_CLOCK_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**
 * @brief System Clock Configuration
 * @note This function is typically generated by STM32CubeMX and configures the system clock source, PLL parameters, and bus clocks.
 *       It is called at the beginning of the main function to set up the system clock for the application.
 */
void SystemClock_Config(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif  // SYSTEM_CLOCK_CONFIG_H_
